// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: notifier.proto

package notifierproto

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Notifier) Validate() error {
	if this.GetNotifier() == nil {
		return github_com_mwitkow_go_proto_validators.FieldError("Notifier", fmt.Errorf("one of the fields must be set"))
	}
	if oneOfNester, ok := this.GetNotifier().(*Notifier_Sms); ok {
		if oneOfNester.Sms != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.Sms); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Sms", err)
			}
		}
	}
	return nil
}
func (this *Notifier_SMS) Validate() error {
	if this.PhoneNumber == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("PhoneNumber", fmt.Errorf(`value '%v' must not be an empty string`, this.PhoneNumber))
	}
	return nil
}
func (this *Message) Validate() error {
	if this.GetMessage() == nil {
		return github_com_mwitkow_go_proto_validators.FieldError("Message", fmt.Errorf("one of the fields must be set"))
	}
	if oneOfNester, ok := this.GetMessage().(*Message_BodyOnly_); ok {
		if oneOfNester.BodyOnly != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(oneOfNester.BodyOnly); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("BodyOnly", err)
			}
		}
	}
	return nil
}
func (this *Message_BodyOnly) Validate() error {
	if this.Body == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Body", fmt.Errorf(`value '%v' must not be an empty string`, this.Body))
	}
	return nil
}
func (this *NotifyRequest) Validate() error {
	if nil == this.Notifier {
		return github_com_mwitkow_go_proto_validators.FieldError("Notifier", fmt.Errorf("message must exist"))
	}
	if this.Notifier != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Notifier); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Notifier", err)
		}
	}
	if nil == this.Message {
		return github_com_mwitkow_go_proto_validators.FieldError("Message", fmt.Errorf("message must exist"))
	}
	if this.Message != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Message); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Message", err)
		}
	}
	return nil
}
func (this *NotifyResponse) Validate() error {
	return nil
}
