// DO NOT EDIT: Client was autogenerated from 'twilio.proto'
package twilioproto

import (
	"context"

	"github.com/edstell/lambda/libraries/rpc"
	"google.golang.org/protobuf/encoding/protojson"
)

type Client struct {
	sendsms   rpc.Invoker
}

func NewClient(i rpc.LambdaInvoker, arn string) *Client {
	return &Client{
		sendsms:   rpc.Client(i, arn, "SendSMS"),
	}
}

func (c *Client) SendSMS(ctx context.Context, req *SendSMSRequest) (*SendSMSResponse, error) {
	payload, err := protojson.Marshal(req)
	if err != nil {
		return nil, err
	}

	rsp, err := c.sendsms.Invoke(ctx, payload)
	if err != nil {
		return nil, err
	}

	out := &SendSMSResponse{}
	if err := protojson.Unmarshal(rsp, out); err != nil {
		return nil, err
	}

	return out, nil
}
