// DO NOT EDIT: Client was autogenerated from 'google/protobuf/descriptor.proto'
package google.protobuf

import (
	"context"

	"github.com/edstell/lambda/libraries/rpc"
	"google.golang.org/protobuf/encoding/protojson"
)
